version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:80"  # Host port 8000 mapped to container port 80
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/aclima_db
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: aclima_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
