version: '3.8'
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:80"  # Host port 8000 mapped to container port 80
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/aclima_db #TODO add secrets integration
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: aclima_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  
      test: ["CMD-SHELL", "PGPASSWORD=pass pg_isready -U user -d aclima_db -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1m
volumes:
  postgres_data:
